version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/api
    overwrite: true

permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: scripts/register_service.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/restart.sh
      timeout: 120
      runas: root
