#spring.config.import=optional:aws-parameterstore:/mathrank/aws/monolith/
#
#spring.profiles.active=develop

spring.profiles.active=develop, init-member, local

spring.config.import=optional:file:.env[.properties]

snowflake.node.id=1

server.jwt.algorithm=HS256
server.jwt.key=qwkdmoqwneoqwjenwqohwqdnqwdnwqouheoquwdiqwbdiqhwbdiqweubidqebieyqgwyegqwihdbqwuidqwbydbqwyevqwiebwqibeyiqwe

auth.jwt.accessToken.expireTimeMillis=1000000
auth.jwt.refreshToken.expireTimeMillis=1000000
server.local.storage=app/api/monolith-api/src/main/resources

spring.web.resources.add-mappings=false

cors.mode=develop

client.problem.host=http://localhost
client.problem.port=8080
client.problem.connection-timeout-seconds=10
client.problem.read-timeout-seconds=10

client.course.host=http://localhost
client.course.port=8080
client.course.connection-timeout-seconds=10
client.course.read-timeout-seconds=10

client.member.host=http://localhost
client.member.port=8080
client.member.connection-timeout-seconds=10
client.member.read-timeout-seconds=10

client.school.connection-timeout-seconds=10
client.school.read-timeout-seconds=10

caffeine.cache.entry.count=200

payment.portone.apiSecret=1223123123123
client.point.readTimeoutSeconds=10000
client.point.connectionTimeoutSeconds=10000