dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'io.portone:server-sdk:0.21.0'

    implementation project(':common:mathrank-exception')
    implementation project(':common:mathrank-outbox')
    implementation project(':common:mathrank-event')
    implementation project(':common:mathrank-dataserializer')
    runtimeOnly 'com.h2database:h2'

    testImplementation project(':common:mathrank-event-publisher-test')
}